# Generated by Django 2.1.4 on 2018-12-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reveiw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('company', models.CharField(max_length=64)),
                ('workingexperience', models.IntegerField()),
                ('date', models.CharField(max_length=64)),
                ('review', models.CharField(max_length=5000)),
                ('rating', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Flight',
        ),
    ]
