# Generated by Django 2.1.4 on 2018-12-19 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20181219_1603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topic',
            name='category',
        ),
        migrations.DeleteModel(
            name='Topic',
        ),
    ]
