# Generated by Django 2.1.4 on 2018-12-19 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0006_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='Question',
            field=models.TextField(),
        ),
        migrations.RemoveField(
            model_name='questions',
            name='category',
        ),
        migrations.AddField(
            model_name='questions',
            name='category',
            field=models.ManyToManyField(blank=True, to='hello.category'),
        ),
    ]
