# Generated by Django 2.1.4 on 2018-12-19 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_auto_20181219_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='companies',
            field=models.ManyToManyField(blank=True, related_name='categories', to='hello.companies'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='questions', to='hello.category'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='topics', to='hello.category'),
        ),
    ]
